### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by MichelZ** [MethodsAndPractices/vsteam#262]
Is there a reason that Code Coverage is disabled?
(`e.g. build/unitTest.yml -> parameters: CodeCoverage: 'false'`)

if not - can this be enabled?

**Comment by SebastianSchuetze** [comment]
Check the following issue:
https://github.com/pester/Pester/issues/1318
and
https://github.com/PowerShell/PowerShell/issues/9884

Since an OS update for windows PS is getting very flow when loading classes. Since the script analyzer is doing that very often, the current build can take very long time (30-50 minutes) because of that.

I think we are dependent from this issue being solved.

**Comment by MichelZ** [comment]
@SebastianSchuetze This has been fixed in `PS Core 6.2.3` according to your link(s), `6.2.4` is currently installed on the [Windows 2019](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md) and [Windows 2016](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2016-Readme.md) images. 

I think we should be good here?

**Comment by SebastianSchuetze** [comment]
I hope that this was also the intention of @DarqueWarrior because of the deactivation. Let's wait for his opinion to be sure that there is nor another reason.

**Comment by DarqueWarrior** [comment]
I can do some testing and see if that has been fixed. The builds were taking way way too long.

**Comment by MichelZ** [comment]
@DarqueWarrior Success?

**Comment by SebastianSchuetze** [comment]
Currently the limitation of code coverage is a limitation due to Pester and PowerShell. So this cannot be improved currently without too much effort (parallelization of unit tests with agents and merging results).

We will see if we find something to improve in the future.
